trigger:
  - main

pool:
  name: Default

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-25.0.2'
      mavenVersionOption: 'Default'
      mavenDirectory: 'C:\Maven'