trigger:
  - main

pool:
  name: Default

steps:
  - checkout: self

  - script: |
      set JAVA_HOME=C:\Program Files\Java\jdk-25.0.2
      set PATH=%JAVA_HOME%\bin;C:\Maven\bin;%PATH%
      mvn --version
      mvn test
    displayName: 'Compilar y ejecutar pruebas con Maven'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: false
    displayName: 'Publicar resultados de pruebas'